

language:
 - cpp

compiler:
 - gcc

os:
 - linux

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq flex build-essential valgrind
 - wget http://mirrors.kernel.org/ubuntu/pool/main/b/bison/bison_3.0.4.dfsg-1_amd64.deb
 - wget http://mirrors.kernel.org/ubuntu/pool/main/b/bison/libbison-dev_3.0.4.dfsg-1_amd64.deb
 - sudo dpkg -i libbison-dev_3.0.4.dfsg-1_amd64.deb
 - sudo dpkg -i bison_3.0.4.dfsg-1_amd64.deb

before_script:
 - make setup
 - make gen-random-tests

script:
 - make
 - make run-regression
 - make run-random-tests

after_success:
 - echo "Success"

after_failure:
 - echo "Failure"

after_script:
 - echo "Script Finished."

