site_name: sat-solver

site_author: Ben Marshall

theme: readthedocs

repo_name: https://github.com/ben-marshall/sat-solver

markdown_extensions:
- smarty
- sane_lists
- footnotes

pages:
- Overview: overview.md
- Theory:
    - AC-3 Algorithm: ac-3.md
    - AC-3 Implementation: ac-3-implementation.md
- Usage: usage.md
- Notes:
    - Implication: implication-notes.md


